name: Versioning

on:
  push:
    branches:
      - developer

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Jordan Esteban Ramirez Mejia"
          git config --global user.email "jordan.ramirezme@amigo.edu.co"

      - name: Create version tag
        run: |
          git tag -a v${{ github.run_number }} -m "Version ${{ github.run_number }}"
          git push origin --tags
